### ISSUE TITLE
Search mode ended when entering "i"

### ISSUE THREAD

**Issue by phlind** [horriblename/preview-mode-keybinds-obsidian#1]
Cool plugin! One bug I nocited: When I enter the search mode and type "i" in the search filed, it's interpreted as "go into edit mode".

**Comment by horriblename** [comment]
Thanks for the feedback! The bug is now fixed in [this commit](https://github.com/horriblename/preview-mode-keybinds-obsidian/commit/3985ba1b679230e20236dd41eea78c2f78981e00)
