### ISSUE TITLE
How to install the plugin?

### ISSUE THREAD

**Issue by sizhky** [horriblename/preview-mode-keybinds-obsidian#8]
I tried manually adding all the repo's files to `.obsidian/plugins/preview-mode-keybindings-obsidian/` folder but getting this error on activating

<img width="354" alt="image" src="https://user-images.githubusercontent.com/3656100/155873755-3433598c-4042-462d-8a9a-da57c12831f0.png">

**Comment by horriblename** [comment]
You only need the "main.js" and "manifest.json" files from the [releases page](https://github.com/horriblename/preview-mode-keybinds-obsidian/releases). 

Move those files to the folder `.obsidian/plugins/preview-mode-keybindings-obsidian/`
